apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 2 # minimum replicas
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: omarshokeir/consumer:latest
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
