version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 2
    ports:
      - "3000:3000" # Only one port will be published, others are internal

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 2
